# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen_main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1015, 768)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(1366, 768))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("cine-info.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 791, 751))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(800, 16777215))
        self.frame.setStyleSheet(_fromUtf8(""))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrollArea = QtGui.QScrollArea(self.frame)
        self.scrollArea.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.scrollArea.setStyleSheet(_fromUtf8("border: None;"))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 758, 950))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(800, 16777215))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.fiction_title_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.fiction_title_2.setWordWrap(True)
        self.fiction_title_2.setObjectName(_fromUtf8("fiction_title_2"))
        self.gridLayout.addWidget(self.fiction_title_2, 30, 2, 1, 1)
        self.label_action_1 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_action_1.setMaximumSize(QtCore.QSize(95, 131))
        self.label_action_1.setAutoFillBackground(False)
        self.label_action_1.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_action_1.setText(_fromUtf8(""))
        self.label_action_1.setTextFormat(QtCore.Qt.RichText)
        self.label_action_1.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_action_1.setScaledContents(True)
        self.label_action_1.setObjectName(_fromUtf8("label_action_1"))
        self.gridLayout.addWidget(self.label_action_1, 1, 1, 1, 1)
        self.label_comedy_0 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_comedy_0.setMaximumSize(QtCore.QSize(95, 131))
        self.label_comedy_0.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_comedy_0.setText(_fromUtf8(""))
        self.label_comedy_0.setTextFormat(QtCore.Qt.RichText)
        self.label_comedy_0.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_comedy_0.setScaledContents(True)
        self.label_comedy_0.setObjectName(_fromUtf8("label_comedy_0"))
        self.gridLayout.addWidget(self.label_comedy_0, 9, 0, 1, 1)
        self.label_romance_1 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_romance_1.setMaximumSize(QtCore.QSize(95, 131))
        self.label_romance_1.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_romance_1.setText(_fromUtf8(""))
        self.label_romance_1.setTextFormat(QtCore.Qt.RichText)
        self.label_romance_1.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_romance_1.setScaledContents(True)
        self.label_romance_1.setObjectName(_fromUtf8("label_romance_1"))
        self.gridLayout.addWidget(self.label_romance_1, 13, 1, 1, 1)
        self.label_drama_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_drama_3.setMaximumSize(QtCore.QSize(95, 131))
        self.label_drama_3.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_drama_3.setText(_fromUtf8(""))
        self.label_drama_3.setTextFormat(QtCore.Qt.RichText)
        self.label_drama_3.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_drama_3.setScaledContents(True)
        self.label_drama_3.setObjectName(_fromUtf8("label_drama_3"))
        self.gridLayout.addWidget(self.label_drama_3, 17, 3, 1, 1)
        self.label_comedy_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_comedy_2.setMaximumSize(QtCore.QSize(95, 131))
        self.label_comedy_2.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_comedy_2.setText(_fromUtf8(""))
        self.label_comedy_2.setTextFormat(QtCore.Qt.RichText)
        self.label_comedy_2.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_comedy_2.setScaledContents(True)
        self.label_comedy_2.setObjectName(_fromUtf8("label_comedy_2"))
        self.gridLayout.addWidget(self.label_comedy_2, 9, 2, 1, 1)
        self.fiction_title_1 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.fiction_title_1.setWordWrap(True)
        self.fiction_title_1.setObjectName(_fromUtf8("fiction_title_1"))
        self.gridLayout.addWidget(self.fiction_title_1, 30, 1, 1, 1)
        self.fiction_title_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.fiction_title_3.setWordWrap(True)
        self.fiction_title_3.setObjectName(_fromUtf8("fiction_title_3"))
        self.gridLayout.addWidget(self.fiction_title_3, 30, 3, 1, 1)
        self.fiction_title_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.fiction_title_4.setWordWrap(True)
        self.fiction_title_4.setObjectName(_fromUtf8("fiction_title_4"))
        self.gridLayout.addWidget(self.fiction_title_4, 30, 4, 1, 1)
        self.label_horror_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_horror_3.setMaximumSize(QtCore.QSize(95, 131))
        self.label_horror_3.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_horror_3.setText(_fromUtf8(""))
        self.label_horror_3.setTextFormat(QtCore.Qt.RichText)
        self.label_horror_3.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_horror_3.setScaledContents(True)
        self.label_horror_3.setObjectName(_fromUtf8("label_horror_3"))
        self.gridLayout.addWidget(self.label_horror_3, 25, 3, 1, 1)
        self.label_horror_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_horror_4.setMaximumSize(QtCore.QSize(95, 131))
        self.label_horror_4.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_horror_4.setText(_fromUtf8(""))
        self.label_horror_4.setTextFormat(QtCore.Qt.RichText)
        self.label_horror_4.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_horror_4.setScaledContents(True)
        self.label_horror_4.setObjectName(_fromUtf8("label_horror_4"))
        self.gridLayout.addWidget(self.label_horror_4, 25, 4, 1, 1)
        self.label_drama_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_drama_2.setMaximumSize(QtCore.QSize(95, 131))
        self.label_drama_2.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_drama_2.setText(_fromUtf8(""))
        self.label_drama_2.setTextFormat(QtCore.Qt.RichText)
        self.label_drama_2.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_drama_2.setScaledContents(True)
        self.label_drama_2.setObjectName(_fromUtf8("label_drama_2"))
        self.gridLayout.addWidget(self.label_drama_2, 17, 2, 1, 1)
        self.label_drama_0 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_drama_0.setMaximumSize(QtCore.QSize(95, 131))
        self.label_drama_0.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_drama_0.setText(_fromUtf8(""))
        self.label_drama_0.setTextFormat(QtCore.Qt.RichText)
        self.label_drama_0.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_drama_0.setScaledContents(True)
        self.label_drama_0.setObjectName(_fromUtf8("label_drama_0"))
        self.gridLayout.addWidget(self.label_drama_0, 17, 0, 1, 1)
        self.lb_cr = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lb_cr.setMaximumSize(QtCore.QSize(200, 35))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lb_cr.setFont(font)
        self.lb_cr.setObjectName(_fromUtf8("lb_cr"))
        self.gridLayout.addWidget(self.lb_cr, 20, 0, 1, 2)
        self.lb_dm = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lb_dm.setMaximumSize(QtCore.QSize(200, 35))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lb_dm.setFont(font)
        self.lb_dm.setObjectName(_fromUtf8("lb_dm"))
        self.gridLayout.addWidget(self.lb_dm, 16, 0, 1, 2)
        self.action_title_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.action_title_4.setWordWrap(True)
        self.action_title_4.setObjectName(_fromUtf8("action_title_4"))
        self.gridLayout.addWidget(self.action_title_4, 2, 4, 1, 1)
        self.command_ac = QtGui.QCommandLinkButton(self.scrollAreaWidgetContents)
        self.command_ac.setMaximumSize(QtCore.QSize(90, 35))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("img/arrow_right.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.command_ac.setIcon(icon1)
        self.command_ac.setObjectName(_fromUtf8("command_ac"))
        self.gridLayout.addWidget(self.command_ac, 3, 3, 1, 1)
        self.label_adventure_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_adventure_4.setMaximumSize(QtCore.QSize(95, 131))
        self.label_adventure_4.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_adventure_4.setText(_fromUtf8(""))
        self.label_adventure_4.setTextFormat(QtCore.Qt.RichText)
        self.label_adventure_4.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_adventure_4.setScaledContents(True)
        self.label_adventure_4.setObjectName(_fromUtf8("label_adventure_4"))
        self.gridLayout.addWidget(self.label_adventure_4, 5, 4, 1, 1)
        self.label_adventure_1 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_adventure_1.setMaximumSize(QtCore.QSize(95, 131))
        self.label_adventure_1.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_adventure_1.setText(_fromUtf8(""))
        self.label_adventure_1.setTextFormat(QtCore.Qt.RichText)
        self.label_adventure_1.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_adventure_1.setScaledContents(True)
        self.label_adventure_1.setObjectName(_fromUtf8("label_adventure_1"))
        self.gridLayout.addWidget(self.label_adventure_1, 5, 1, 1, 1)
        self.label_comedy_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_comedy_4.setMaximumSize(QtCore.QSize(95, 131))
        self.label_comedy_4.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_comedy_4.setText(_fromUtf8(""))
        self.label_comedy_4.setTextFormat(QtCore.Qt.RichText)
        self.label_comedy_4.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_comedy_4.setScaledContents(True)
        self.label_comedy_4.setObjectName(_fromUtf8("label_comedy_4"))
        self.gridLayout.addWidget(self.label_comedy_4, 9, 4, 1, 1)
        self.romance_title_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.romance_title_3.setWordWrap(True)
        self.romance_title_3.setObjectName(_fromUtf8("romance_title_3"))
        self.gridLayout.addWidget(self.romance_title_3, 14, 3, 1, 1)
        self.label_fiction_1 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_fiction_1.setMaximumSize(QtCore.QSize(95, 131))
        self.label_fiction_1.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_fiction_1.setText(_fromUtf8(""))
        self.label_fiction_1.setTextFormat(QtCore.Qt.RichText)
        self.label_fiction_1.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_fiction_1.setScaledContents(True)
        self.label_fiction_1.setObjectName(_fromUtf8("label_fiction_1"))
        self.gridLayout.addWidget(self.label_fiction_1, 29, 1, 1, 1)
        self.label_fiction_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_fiction_2.setMaximumSize(QtCore.QSize(95, 131))
        self.label_fiction_2.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_fiction_2.setText(_fromUtf8(""))
        self.label_fiction_2.setTextFormat(QtCore.Qt.RichText)
        self.label_fiction_2.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_fiction_2.setScaledContents(True)
        self.label_fiction_2.setObjectName(_fromUtf8("label_fiction_2"))
        self.gridLayout.addWidget(self.label_fiction_2, 29, 2, 1, 1)
        self.label_action_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_action_4.setMaximumSize(QtCore.QSize(95, 131))
        self.label_action_4.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_action_4.setText(_fromUtf8(""))
        self.label_action_4.setTextFormat(QtCore.Qt.RichText)
        self.label_action_4.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_action_4.setScaledContents(True)
        self.label_action_4.setObjectName(_fromUtf8("label_action_4"))
        self.gridLayout.addWidget(self.label_action_4, 1, 4, 1, 1)
        self.label_action_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_action_3.setMaximumSize(QtCore.QSize(95, 131))
        self.label_action_3.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_action_3.setText(_fromUtf8(""))
        self.label_action_3.setTextFormat(QtCore.Qt.RichText)
        self.label_action_3.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_action_3.setScaledContents(True)
        self.label_action_3.setObjectName(_fromUtf8("label_action_3"))
        self.gridLayout.addWidget(self.label_action_3, 1, 3, 1, 1)
        self.drama_title_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.drama_title_4.setWordWrap(True)
        self.drama_title_4.setObjectName(_fromUtf8("drama_title_4"))
        self.gridLayout.addWidget(self.drama_title_4, 18, 4, 1, 1)
        self.lb_av = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lb_av.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lb_av.setFont(font)
        self.lb_av.setObjectName(_fromUtf8("lb_av"))
        self.gridLayout.addWidget(self.lb_av, 4, 0, 1, 2)
        self.drama_title_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.drama_title_3.setWordWrap(True)
        self.drama_title_3.setObjectName(_fromUtf8("drama_title_3"))
        self.gridLayout.addWidget(self.drama_title_3, 18, 3, 1, 1)
        self.label_romance_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_romance_3.setMaximumSize(QtCore.QSize(95, 131))
        self.label_romance_3.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_romance_3.setText(_fromUtf8(""))
        self.label_romance_3.setTextFormat(QtCore.Qt.RichText)
        self.label_romance_3.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_romance_3.setScaledContents(True)
        self.label_romance_3.setObjectName(_fromUtf8("label_romance_3"))
        self.gridLayout.addWidget(self.label_romance_3, 13, 3, 1, 1)
        self.lb_rm = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lb_rm.setMaximumSize(QtCore.QSize(200, 35))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lb_rm.setFont(font)
        self.lb_rm.setObjectName(_fromUtf8("lb_rm"))
        self.gridLayout.addWidget(self.lb_rm, 12, 0, 1, 2)
        self.label_horror_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_horror_2.setMaximumSize(QtCore.QSize(95, 131))
        self.label_horror_2.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_horror_2.setText(_fromUtf8(""))
        self.label_horror_2.setTextFormat(QtCore.Qt.RichText)
        self.label_horror_2.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_horror_2.setScaledContents(True)
        self.label_horror_2.setObjectName(_fromUtf8("label_horror_2"))
        self.gridLayout.addWidget(self.label_horror_2, 25, 2, 1, 1)
        self.comedy_title_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.comedy_title_2.setWordWrap(True)
        self.comedy_title_2.setObjectName(_fromUtf8("comedy_title_2"))
        self.gridLayout.addWidget(self.comedy_title_2, 10, 2, 1, 1)
        self.adventure_title_1 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.adventure_title_1.setWordWrap(True)
        self.adventure_title_1.setObjectName(_fromUtf8("adventure_title_1"))
        self.gridLayout.addWidget(self.adventure_title_1, 6, 1, 1, 1)
        self.romance_title_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.romance_title_2.setWordWrap(True)
        self.romance_title_2.setObjectName(_fromUtf8("romance_title_2"))
        self.gridLayout.addWidget(self.romance_title_2, 14, 2, 1, 1)
        self.label_crime_1 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_crime_1.setMaximumSize(QtCore.QSize(95, 131))
        self.label_crime_1.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_crime_1.setText(_fromUtf8(""))
        self.label_crime_1.setTextFormat(QtCore.Qt.RichText)
        self.label_crime_1.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_crime_1.setScaledContents(True)
        self.label_crime_1.setObjectName(_fromUtf8("label_crime_1"))
        self.gridLayout.addWidget(self.label_crime_1, 21, 1, 1, 1)
        self.label_crime_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_crime_4.setMaximumSize(QtCore.QSize(95, 131))
        self.label_crime_4.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_crime_4.setText(_fromUtf8(""))
        self.label_crime_4.setTextFormat(QtCore.Qt.RichText)
        self.label_crime_4.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_crime_4.setScaledContents(True)
        self.label_crime_4.setObjectName(_fromUtf8("label_crime_4"))
        self.gridLayout.addWidget(self.label_crime_4, 21, 4, 1, 1)
        self.lb_ac = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lb_ac.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lb_ac.setFont(font)
        self.lb_ac.setObjectName(_fromUtf8("lb_ac"))
        self.gridLayout.addWidget(self.lb_ac, 0, 0, 1, 2)
        self.crime_title_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.crime_title_2.setWordWrap(True)
        self.crime_title_2.setObjectName(_fromUtf8("crime_title_2"))
        self.gridLayout.addWidget(self.crime_title_2, 22, 2, 1, 1)
        self.comedy_title_1 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.comedy_title_1.setWordWrap(True)
        self.comedy_title_1.setObjectName(_fromUtf8("comedy_title_1"))
        self.gridLayout.addWidget(self.comedy_title_1, 10, 1, 1, 1)
        self.label_comedy_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_comedy_3.setMaximumSize(QtCore.QSize(95, 131))
        self.label_comedy_3.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_comedy_3.setText(_fromUtf8(""))
        self.label_comedy_3.setTextFormat(QtCore.Qt.RichText)
        self.label_comedy_3.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_comedy_3.setScaledContents(True)
        self.label_comedy_3.setObjectName(_fromUtf8("label_comedy_3"))
        self.gridLayout.addWidget(self.label_comedy_3, 9, 3, 1, 1)
        self.romance_title_0 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.romance_title_0.setWordWrap(True)
        self.romance_title_0.setObjectName(_fromUtf8("romance_title_0"))
        self.gridLayout.addWidget(self.romance_title_0, 14, 0, 1, 1)
        self.adventure_title_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.adventure_title_3.setWordWrap(True)
        self.adventure_title_3.setObjectName(_fromUtf8("adventure_title_3"))
        self.gridLayout.addWidget(self.adventure_title_3, 6, 3, 1, 1)
        self.horror_title_0 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.horror_title_0.setWordWrap(True)
        self.horror_title_0.setObjectName(_fromUtf8("horror_title_0"))
        self.gridLayout.addWidget(self.horror_title_0, 26, 0, 1, 1)
        self.horror_title_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.horror_title_3.setWordWrap(True)
        self.horror_title_3.setObjectName(_fromUtf8("horror_title_3"))
        self.gridLayout.addWidget(self.horror_title_3, 26, 3, 1, 1)
        self.romance_title_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.romance_title_4.setWordWrap(True)
        self.romance_title_4.setObjectName(_fromUtf8("romance_title_4"))
        self.gridLayout.addWidget(self.romance_title_4, 14, 4, 1, 1)
        self.label_drama_1 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_drama_1.setMaximumSize(QtCore.QSize(95, 131))
        self.label_drama_1.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_drama_1.setText(_fromUtf8(""))
        self.label_drama_1.setTextFormat(QtCore.Qt.RichText)
        self.label_drama_1.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_drama_1.setScaledContents(True)
        self.label_drama_1.setObjectName(_fromUtf8("label_drama_1"))
        self.gridLayout.addWidget(self.label_drama_1, 17, 1, 1, 1)
        self.adventure_title_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.adventure_title_4.setWordWrap(True)
        self.adventure_title_4.setObjectName(_fromUtf8("adventure_title_4"))
        self.gridLayout.addWidget(self.adventure_title_4, 6, 4, 1, 1)
        self.label_horror_0 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_horror_0.setMaximumSize(QtCore.QSize(95, 131))
        self.label_horror_0.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_horror_0.setText(_fromUtf8(""))
        self.label_horror_0.setTextFormat(QtCore.Qt.RichText)
        self.label_horror_0.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_horror_0.setScaledContents(True)
        self.label_horror_0.setObjectName(_fromUtf8("label_horror_0"))
        self.gridLayout.addWidget(self.label_horror_0, 25, 0, 1, 1)
        self.label_horror_1 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_horror_1.setMaximumSize(QtCore.QSize(95, 131))
        self.label_horror_1.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_horror_1.setText(_fromUtf8(""))
        self.label_horror_1.setTextFormat(QtCore.Qt.RichText)
        self.label_horror_1.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_horror_1.setScaledContents(True)
        self.label_horror_1.setObjectName(_fromUtf8("label_horror_1"))
        self.gridLayout.addWidget(self.label_horror_1, 25, 1, 1, 1)
        self.label_adventure_0 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_adventure_0.setMaximumSize(QtCore.QSize(95, 131))
        self.label_adventure_0.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_adventure_0.setText(_fromUtf8(""))
        self.label_adventure_0.setTextFormat(QtCore.Qt.RichText)
        self.label_adventure_0.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_adventure_0.setScaledContents(True)
        self.label_adventure_0.setObjectName(_fromUtf8("label_adventure_0"))
        self.gridLayout.addWidget(self.label_adventure_0, 5, 0, 1, 1)
        self.crime_title_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.crime_title_4.setWordWrap(True)
        self.crime_title_4.setObjectName(_fromUtf8("crime_title_4"))
        self.gridLayout.addWidget(self.crime_title_4, 22, 4, 1, 1)
        self.crime_title_0 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.crime_title_0.setWordWrap(True)
        self.crime_title_0.setObjectName(_fromUtf8("crime_title_0"))
        self.gridLayout.addWidget(self.crime_title_0, 22, 0, 1, 1)
        self.label_adventure_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_adventure_2.setMaximumSize(QtCore.QSize(95, 131))
        self.label_adventure_2.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_adventure_2.setText(_fromUtf8(""))
        self.label_adventure_2.setTextFormat(QtCore.Qt.RichText)
        self.label_adventure_2.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_adventure_2.setScaledContents(True)
        self.label_adventure_2.setObjectName(_fromUtf8("label_adventure_2"))
        self.gridLayout.addWidget(self.label_adventure_2, 5, 2, 1, 1)
        self.action_title_1 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.action_title_1.setAutoFillBackground(False)
        self.action_title_1.setWordWrap(True)
        self.action_title_1.setObjectName(_fromUtf8("action_title_1"))
        self.gridLayout.addWidget(self.action_title_1, 2, 1, 1, 1)
        self.romance_title_1 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.romance_title_1.setWordWrap(True)
        self.romance_title_1.setObjectName(_fromUtf8("romance_title_1"))
        self.gridLayout.addWidget(self.romance_title_1, 14, 1, 1, 1)
        self.label_crime_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_crime_2.setMaximumSize(QtCore.QSize(95, 131))
        self.label_crime_2.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_crime_2.setText(_fromUtf8(""))
        self.label_crime_2.setTextFormat(QtCore.Qt.RichText)
        self.label_crime_2.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_crime_2.setScaledContents(True)
        self.label_crime_2.setObjectName(_fromUtf8("label_crime_2"))
        self.gridLayout.addWidget(self.label_crime_2, 21, 2, 1, 1)
        self.label_action_0 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_action_0.setMaximumSize(QtCore.QSize(95, 131))
        self.label_action_0.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_action_0.setText(_fromUtf8(""))
        self.label_action_0.setTextFormat(QtCore.Qt.RichText)
        self.label_action_0.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_action_0.setScaledContents(True)
        self.label_action_0.setObjectName(_fromUtf8("label_action_0"))
        self.gridLayout.addWidget(self.label_action_0, 1, 0, 1, 1)
        self.action_title_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.action_title_2.setWordWrap(True)
        self.action_title_2.setObjectName(_fromUtf8("action_title_2"))
        self.gridLayout.addWidget(self.action_title_2, 2, 2, 1, 1)
        self.horror_title_1 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.horror_title_1.setWordWrap(True)
        self.horror_title_1.setObjectName(_fromUtf8("horror_title_1"))
        self.gridLayout.addWidget(self.horror_title_1, 26, 1, 1, 1)
        self.horror_title_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.horror_title_2.setWordWrap(True)
        self.horror_title_2.setObjectName(_fromUtf8("horror_title_2"))
        self.gridLayout.addWidget(self.horror_title_2, 26, 2, 1, 1)
        self.label_crime_0 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_crime_0.setMaximumSize(QtCore.QSize(95, 131))
        self.label_crime_0.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_crime_0.setText(_fromUtf8(""))
        self.label_crime_0.setTextFormat(QtCore.Qt.RichText)
        self.label_crime_0.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_crime_0.setScaledContents(True)
        self.label_crime_0.setObjectName(_fromUtf8("label_crime_0"))
        self.gridLayout.addWidget(self.label_crime_0, 21, 0, 1, 1)
        self.horror_title_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.horror_title_4.setWordWrap(True)
        self.horror_title_4.setObjectName(_fromUtf8("horror_title_4"))
        self.gridLayout.addWidget(self.horror_title_4, 26, 4, 1, 1)
        self.crime_title_1 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.crime_title_1.setWordWrap(True)
        self.crime_title_1.setObjectName(_fromUtf8("crime_title_1"))
        self.gridLayout.addWidget(self.crime_title_1, 22, 1, 1, 1)
        self.label_romance_0 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_romance_0.setMaximumSize(QtCore.QSize(95, 131))
        self.label_romance_0.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_romance_0.setText(_fromUtf8(""))
        self.label_romance_0.setTextFormat(QtCore.Qt.RichText)
        self.label_romance_0.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_romance_0.setScaledContents(True)
        self.label_romance_0.setObjectName(_fromUtf8("label_romance_0"))
        self.gridLayout.addWidget(self.label_romance_0, 13, 0, 1, 1)
        self.label_fiction_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_fiction_3.setMaximumSize(QtCore.QSize(95, 131))
        self.label_fiction_3.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_fiction_3.setText(_fromUtf8(""))
        self.label_fiction_3.setTextFormat(QtCore.Qt.RichText)
        self.label_fiction_3.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_fiction_3.setScaledContents(True)
        self.label_fiction_3.setObjectName(_fromUtf8("label_fiction_3"))
        self.gridLayout.addWidget(self.label_fiction_3, 29, 3, 1, 1)
        self.label_fiction_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_fiction_4.setMaximumSize(QtCore.QSize(95, 131))
        self.label_fiction_4.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_fiction_4.setText(_fromUtf8(""))
        self.label_fiction_4.setTextFormat(QtCore.Qt.RichText)
        self.label_fiction_4.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_fiction_4.setScaledContents(True)
        self.label_fiction_4.setObjectName(_fromUtf8("label_fiction_4"))
        self.gridLayout.addWidget(self.label_fiction_4, 29, 4, 1, 1)
        self.fiction_title_0 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.fiction_title_0.setWordWrap(True)
        self.fiction_title_0.setObjectName(_fromUtf8("fiction_title_0"))
        self.gridLayout.addWidget(self.fiction_title_0, 30, 0, 1, 1)
        self.comedy_title_0 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.comedy_title_0.setWordWrap(True)
        self.comedy_title_0.setObjectName(_fromUtf8("comedy_title_0"))
        self.gridLayout.addWidget(self.comedy_title_0, 10, 0, 1, 1)
        self.drama_title_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.drama_title_2.setWordWrap(True)
        self.drama_title_2.setObjectName(_fromUtf8("drama_title_2"))
        self.gridLayout.addWidget(self.drama_title_2, 18, 2, 1, 1)
        self.label_action_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_action_2.setMaximumSize(QtCore.QSize(95, 131))
        self.label_action_2.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_action_2.setText(_fromUtf8(""))
        self.label_action_2.setTextFormat(QtCore.Qt.RichText)
        self.label_action_2.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_action_2.setScaledContents(True)
        self.label_action_2.setObjectName(_fromUtf8("label_action_2"))
        self.gridLayout.addWidget(self.label_action_2, 1, 2, 1, 1)
        self.drama_title_1 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.drama_title_1.setWordWrap(True)
        self.drama_title_1.setObjectName(_fromUtf8("drama_title_1"))
        self.gridLayout.addWidget(self.drama_title_1, 18, 1, 1, 1)
        self.label_romance_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_romance_2.setMaximumSize(QtCore.QSize(95, 131))
        self.label_romance_2.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_romance_2.setText(_fromUtf8(""))
        self.label_romance_2.setTextFormat(QtCore.Qt.RichText)
        self.label_romance_2.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_romance_2.setScaledContents(True)
        self.label_romance_2.setObjectName(_fromUtf8("label_romance_2"))
        self.gridLayout.addWidget(self.label_romance_2, 13, 2, 1, 1)
        self.comedy_title_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.comedy_title_3.setWordWrap(True)
        self.comedy_title_3.setObjectName(_fromUtf8("comedy_title_3"))
        self.gridLayout.addWidget(self.comedy_title_3, 10, 3, 1, 1)
        self.label_adventure_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_adventure_3.setMaximumSize(QtCore.QSize(95, 131))
        self.label_adventure_3.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_adventure_3.setText(_fromUtf8(""))
        self.label_adventure_3.setTextFormat(QtCore.Qt.RichText)
        self.label_adventure_3.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_adventure_3.setScaledContents(True)
        self.label_adventure_3.setObjectName(_fromUtf8("label_adventure_3"))
        self.gridLayout.addWidget(self.label_adventure_3, 5, 3, 1, 1)
        self.label_drama_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_drama_4.setMaximumSize(QtCore.QSize(95, 131))
        self.label_drama_4.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_drama_4.setText(_fromUtf8(""))
        self.label_drama_4.setTextFormat(QtCore.Qt.RichText)
        self.label_drama_4.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_drama_4.setScaledContents(True)
        self.label_drama_4.setObjectName(_fromUtf8("label_drama_4"))
        self.gridLayout.addWidget(self.label_drama_4, 17, 4, 1, 1)
        self.label_crime_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_crime_3.setMaximumSize(QtCore.QSize(95, 131))
        self.label_crime_3.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_crime_3.setText(_fromUtf8(""))
        self.label_crime_3.setTextFormat(QtCore.Qt.RichText)
        self.label_crime_3.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_crime_3.setScaledContents(True)
        self.label_crime_3.setObjectName(_fromUtf8("label_crime_3"))
        self.gridLayout.addWidget(self.label_crime_3, 21, 3, 1, 1)
        self.lb_fic = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lb_fic.setMaximumSize(QtCore.QSize(280, 35))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lb_fic.setFont(font)
        self.lb_fic.setObjectName(_fromUtf8("lb_fic"))
        self.gridLayout.addWidget(self.lb_fic, 28, 0, 1, 3)
        self.label_fiction_0 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_fiction_0.setMaximumSize(QtCore.QSize(95, 131))
        self.label_fiction_0.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_fiction_0.setText(_fromUtf8(""))
        self.label_fiction_0.setTextFormat(QtCore.Qt.RichText)
        self.label_fiction_0.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_fiction_0.setScaledContents(True)
        self.label_fiction_0.setObjectName(_fromUtf8("label_fiction_0"))
        self.gridLayout.addWidget(self.label_fiction_0, 29, 0, 1, 1)
        self.crime_title_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.crime_title_3.setWordWrap(True)
        self.crime_title_3.setObjectName(_fromUtf8("crime_title_3"))
        self.gridLayout.addWidget(self.crime_title_3, 22, 3, 1, 1)
        self.action_title_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.action_title_3.setWordWrap(True)
        self.action_title_3.setObjectName(_fromUtf8("action_title_3"))
        self.gridLayout.addWidget(self.action_title_3, 2, 3, 1, 1)
        self.lb_hr = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lb_hr.setMaximumSize(QtCore.QSize(200, 35))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lb_hr.setFont(font)
        self.lb_hr.setObjectName(_fromUtf8("lb_hr"))
        self.gridLayout.addWidget(self.lb_hr, 24, 0, 1, 2)
        self.label_romance_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_romance_4.setMaximumSize(QtCore.QSize(95, 131))
        self.label_romance_4.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_romance_4.setText(_fromUtf8(""))
        self.label_romance_4.setTextFormat(QtCore.Qt.RichText)
        self.label_romance_4.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_romance_4.setScaledContents(True)
        self.label_romance_4.setObjectName(_fromUtf8("label_romance_4"))
        self.gridLayout.addWidget(self.label_romance_4, 13, 4, 1, 1)
        self.drama_title_0 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.drama_title_0.setWordWrap(True)
        self.drama_title_0.setObjectName(_fromUtf8("drama_title_0"))
        self.gridLayout.addWidget(self.drama_title_0, 18, 0, 1, 1)
        self.label_comedy_1 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_comedy_1.setMaximumSize(QtCore.QSize(95, 131))
        self.label_comedy_1.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius: 3px;"))
        self.label_comedy_1.setText(_fromUtf8(""))
        self.label_comedy_1.setTextFormat(QtCore.Qt.RichText)
        self.label_comedy_1.setPixmap(QtGui.QPixmap(_fromUtf8("background-white.png")))
        self.label_comedy_1.setScaledContents(True)
        self.label_comedy_1.setObjectName(_fromUtf8("label_comedy_1"))
        self.gridLayout.addWidget(self.label_comedy_1, 9, 1, 1, 1)
        self.adventure_title_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.adventure_title_2.setWordWrap(True)
        self.adventure_title_2.setObjectName(_fromUtf8("adventure_title_2"))
        self.gridLayout.addWidget(self.adventure_title_2, 6, 2, 1, 1)
        self.action_title_0 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.action_title_0.setWordWrap(True)
        self.action_title_0.setObjectName(_fromUtf8("action_title_0"))
        self.gridLayout.addWidget(self.action_title_0, 2, 0, 1, 1)
        self.adventure_title_0 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.adventure_title_0.setWordWrap(True)
        self.adventure_title_0.setObjectName(_fromUtf8("adventure_title_0"))
        self.gridLayout.addWidget(self.adventure_title_0, 6, 0, 1, 1)
        self.lb_cm = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lb_cm.setMaximumSize(QtCore.QSize(200, 35))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lb_cm.setFont(font)
        self.lb_cm.setObjectName(_fromUtf8("lb_cm"))
        self.gridLayout.addWidget(self.lb_cm, 8, 0, 1, 2)
        self.comedy_title_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.comedy_title_4.setWordWrap(True)
        self.comedy_title_4.setObjectName(_fromUtf8("comedy_title_4"))
        self.gridLayout.addWidget(self.comedy_title_4, 10, 4, 1, 1)
        self.command_ac_bk = QtGui.QCommandLinkButton(self.scrollAreaWidgetContents)
        self.command_ac_bk.setMaximumSize(QtCore.QSize(90, 35))
        self.command_ac_bk.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("img/arrow_left.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.command_ac_bk.setIcon(icon2)
        self.command_ac_bk.setObjectName(_fromUtf8("command_ac_bk"))
        self.gridLayout.addWidget(self.command_ac_bk, 3, 1, 1, 1)
        self.command_av = QtGui.QCommandLinkButton(self.scrollAreaWidgetContents)
        self.command_av.setMaximumSize(QtCore.QSize(90, 35))
        self.command_av.setIcon(icon1)
        self.command_av.setObjectName(_fromUtf8("command_av"))
        self.gridLayout.addWidget(self.command_av, 7, 3, 1, 1)
        self.command_av_bk = QtGui.QCommandLinkButton(self.scrollAreaWidgetContents)
        self.command_av_bk.setMaximumSize(QtCore.QSize(90, 35))
        self.command_av_bk.setIcon(icon2)
        self.command_av_bk.setObjectName(_fromUtf8("command_av_bk"))
        self.gridLayout.addWidget(self.command_av_bk, 7, 1, 1, 1)
        self.command_cm_bk = QtGui.QCommandLinkButton(self.scrollAreaWidgetContents)
        self.command_cm_bk.setMaximumSize(QtCore.QSize(100, 30))
        self.command_cm_bk.setIcon(icon2)
        self.command_cm_bk.setObjectName(_fromUtf8("command_cm_bk"))
        self.gridLayout.addWidget(self.command_cm_bk, 11, 1, 1, 1)
        self.command_cm = QtGui.QCommandLinkButton(self.scrollAreaWidgetContents)
        self.command_cm.setMaximumSize(QtCore.QSize(100, 30))
        self.command_cm.setIcon(icon1)
        self.command_cm.setObjectName(_fromUtf8("command_cm"))
        self.gridLayout.addWidget(self.command_cm, 11, 3, 1, 1)
        self.command_rm = QtGui.QCommandLinkButton(self.scrollAreaWidgetContents)
        self.command_rm.setMaximumSize(QtCore.QSize(100, 30))
        self.command_rm.setIcon(icon1)
        self.command_rm.setObjectName(_fromUtf8("command_rm"))
        self.gridLayout.addWidget(self.command_rm, 15, 3, 1, 1)
        self.command_rm_bk = QtGui.QCommandLinkButton(self.scrollAreaWidgetContents)
        self.command_rm_bk.setMaximumSize(QtCore.QSize(100, 30))
        self.command_rm_bk.setIcon(icon2)
        self.command_rm_bk.setObjectName(_fromUtf8("command_rm_bk"))
        self.gridLayout.addWidget(self.command_rm_bk, 15, 1, 1, 1)
        self.command_dm = QtGui.QCommandLinkButton(self.scrollAreaWidgetContents)
        self.command_dm.setMaximumSize(QtCore.QSize(100, 30))
        self.command_dm.setIcon(icon1)
        self.command_dm.setObjectName(_fromUtf8("command_dm"))
        self.gridLayout.addWidget(self.command_dm, 19, 3, 1, 1)
        self.command_dm_bk = QtGui.QCommandLinkButton(self.scrollAreaWidgetContents)
        self.command_dm_bk.setMaximumSize(QtCore.QSize(100, 30))
        self.command_dm_bk.setIcon(icon2)
        self.command_dm_bk.setObjectName(_fromUtf8("command_dm_bk"))
        self.gridLayout.addWidget(self.command_dm_bk, 19, 1, 1, 1)
        self.command_cr_bk = QtGui.QCommandLinkButton(self.scrollAreaWidgetContents)
        self.command_cr_bk.setMaximumSize(QtCore.QSize(100, 30))
        self.command_cr_bk.setIcon(icon2)
        self.command_cr_bk.setObjectName(_fromUtf8("command_cr_bk"))
        self.gridLayout.addWidget(self.command_cr_bk, 23, 1, 1, 1)
        self.command_cr = QtGui.QCommandLinkButton(self.scrollAreaWidgetContents)
        self.command_cr.setMaximumSize(QtCore.QSize(100, 30))
        self.command_cr.setIcon(icon1)
        self.command_cr.setObjectName(_fromUtf8("command_cr"))
        self.gridLayout.addWidget(self.command_cr, 23, 3, 1, 1)
        self.command_hr_bk = QtGui.QCommandLinkButton(self.scrollAreaWidgetContents)
        self.command_hr_bk.setMaximumSize(QtCore.QSize(100, 30))
        self.command_hr_bk.setIcon(icon2)
        self.command_hr_bk.setObjectName(_fromUtf8("command_hr_bk"))
        self.gridLayout.addWidget(self.command_hr_bk, 27, 1, 1, 1)
        self.command_hr = QtGui.QCommandLinkButton(self.scrollAreaWidgetContents)
        self.command_hr.setMaximumSize(QtCore.QSize(100, 30))
        self.command_hr.setIcon(icon1)
        self.command_hr.setObjectName(_fromUtf8("command_hr"))
        self.gridLayout.addWidget(self.command_hr, 27, 3, 1, 1)
        self.command_fic_bk = QtGui.QCommandLinkButton(self.scrollAreaWidgetContents)
        self.command_fic_bk.setMaximumSize(QtCore.QSize(100, 30))
        self.command_fic_bk.setIcon(icon2)
        self.command_fic_bk.setObjectName(_fromUtf8("command_fic_bk"))
        self.gridLayout.addWidget(self.command_fic_bk, 31, 1, 1, 1)
        self.command_fic = QtGui.QCommandLinkButton(self.scrollAreaWidgetContents)
        self.command_fic.setMaximumSize(QtCore.QSize(100, 30))
        self.command_fic.setIcon(icon1)
        self.command_fic.setObjectName(_fromUtf8("command_fic"))
        self.gridLayout.addWidget(self.command_fic, 31, 3, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(800, 0, 211, 711))
        self.frame_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.info_name = QtGui.QLabel(self.frame_2)
        self.info_name.setGeometry(QtCore.QRect(10, 150, 141, 61))
        self.info_name.setWordWrap(True)
        self.info_name.setObjectName(_fromUtf8("info_name"))
        self.info_poster = QtGui.QLabel(self.frame_2)
        self.info_poster.setGeometry(QtCore.QRect(40, 10, 95, 131))
        self.info_poster.setMaximumSize(QtCore.QSize(95, 131))
        self.info_poster.setText(_fromUtf8(""))
        self.info_poster.setTextFormat(QtCore.Qt.RichText)
        self.info_poster.setScaledContents(True)
        self.info_poster.setWordWrap(True)
        self.info_poster.setObjectName(_fromUtf8("info_poster"))
        self.info_overview = QtGui.QLabel(self.frame_2)
        self.info_overview.setGeometry(QtCore.QRect(10, 230, 191, 351))
        self.info_overview.setWordWrap(True)
        self.info_overview.setObjectName(_fromUtf8("info_overview"))
        self.info_date_2 = QtGui.QLabel(self.frame_2)
        self.info_date_2.setGeometry(QtCore.QRect(120, 660, 91, 20))
        self.info_date_2.setText(_fromUtf8(""))
        self.info_date_2.setWordWrap(True)
        self.info_date_2.setObjectName(_fromUtf8("info_date_2"))
        self.info_vote_2 = QtGui.QLabel(self.frame_2)
        self.info_vote_2.setGeometry(QtCore.QRect(120, 630, 81, 20))
        self.info_vote_2.setText(_fromUtf8(""))
        self.info_vote_2.setWordWrap(True)
        self.info_vote_2.setObjectName(_fromUtf8("info_vote_2"))
        self.info_vote = QtGui.QLabel(self.frame_2)
        self.info_vote.setGeometry(QtCore.QRect(10, 630, 101, 17))
        self.info_vote.setWordWrap(True)
        self.info_vote.setObjectName(_fromUtf8("info_vote"))
        self.info_date = QtGui.QLabel(self.frame_2)
        self.info_date.setGeometry(QtCore.QRect(10, 660, 101, 17))
        self.info_date.setWordWrap(True)
        self.info_date.setObjectName(_fromUtf8("info_date"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(783, 0, 21, 701))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "CineInfo", None))
        self.fiction_title_2.setText(_translate("MainWindow", "TextLabel", None))
        self.fiction_title_1.setText(_translate("MainWindow", "TextLabel", None))
        self.fiction_title_3.setText(_translate("MainWindow", "TextLabel", None))
        self.fiction_title_4.setText(_translate("MainWindow", "TextLabel", None))
        self.lb_cr.setText(_translate("MainWindow", "Crime Movies", None))
        self.lb_dm.setText(_translate("MainWindow", "Drama Movies", None))
        self.action_title_4.setText(_translate("MainWindow", "TextLabel", None))
        self.command_ac.setText(_translate("MainWindow", "More", None))
        self.romance_title_3.setText(_translate("MainWindow", "TextLabel", None))
        self.drama_title_4.setText(_translate("MainWindow", "TextLabel", None))
        self.lb_av.setText(_translate("MainWindow", "Adventure Movies", None))
        self.drama_title_3.setText(_translate("MainWindow", "TextLabel", None))
        self.lb_rm.setText(_translate("MainWindow", "Romance Movies", None))
        self.comedy_title_2.setText(_translate("MainWindow", "TextLabel", None))
        self.adventure_title_1.setText(_translate("MainWindow", "TextLabel", None))
        self.romance_title_2.setText(_translate("MainWindow", "TextLabel", None))
        self.lb_ac.setText(_translate("MainWindow", "Action Movies", None))
        self.crime_title_2.setText(_translate("MainWindow", "TextLabel", None))
        self.comedy_title_1.setText(_translate("MainWindow", "TextLabel", None))
        self.romance_title_0.setText(_translate("MainWindow", "TextLabel", None))
        self.adventure_title_3.setText(_translate("MainWindow", "TextLabel", None))
        self.horror_title_0.setText(_translate("MainWindow", "TextLabel", None))
        self.horror_title_3.setText(_translate("MainWindow", "TextLabel", None))
        self.romance_title_4.setText(_translate("MainWindow", "TextLabel", None))
        self.adventure_title_4.setText(_translate("MainWindow", "TextLabel", None))
        self.crime_title_4.setText(_translate("MainWindow", "TextLabel", None))
        self.crime_title_0.setText(_translate("MainWindow", "TextLabel", None))
        self.action_title_1.setText(_translate("MainWindow", "TextLabel", None))
        self.romance_title_1.setText(_translate("MainWindow", "TextLabel", None))
        self.action_title_2.setText(_translate("MainWindow", "TextLabel", None))
        self.horror_title_1.setText(_translate("MainWindow", "TextLabel", None))
        self.horror_title_2.setText(_translate("MainWindow", "TextLabel", None))
        self.horror_title_4.setText(_translate("MainWindow", "TextLabel", None))
        self.crime_title_1.setText(_translate("MainWindow", "TextLabel", None))
        self.fiction_title_0.setText(_translate("MainWindow", "TextLabel", None))
        self.comedy_title_0.setText(_translate("MainWindow", "TextLabel", None))
        self.drama_title_2.setText(_translate("MainWindow", "TextLabel", None))
        self.drama_title_1.setText(_translate("MainWindow", "TextLabel", None))
        self.comedy_title_3.setText(_translate("MainWindow", "TextLabel", None))
        self.lb_fic.setText(_translate("MainWindow", "Science Fiction Movies", None))
        self.crime_title_3.setText(_translate("MainWindow", "TextLabel", None))
        self.action_title_3.setText(_translate("MainWindow", "TextLabel", None))
        self.lb_hr.setText(_translate("MainWindow", "Horror Movies", None))
        self.drama_title_0.setText(_translate("MainWindow", "TextLabel", None))
        self.adventure_title_2.setText(_translate("MainWindow", "TextLabel", None))
        self.action_title_0.setText(_translate("MainWindow", "TextLabel", None))
        self.adventure_title_0.setText(_translate("MainWindow", "TextLabel", None))
        self.lb_cm.setText(_translate("MainWindow", "Comedy Movies", None))
        self.comedy_title_4.setText(_translate("MainWindow", "TextLabel", None))
        self.command_ac_bk.setText(_translate("MainWindow", "Back", None))
        self.command_av.setText(_translate("MainWindow", "More", None))
        self.command_av_bk.setText(_translate("MainWindow", "Back", None))
        self.command_cm_bk.setText(_translate("MainWindow", "Back", None))
        self.command_cm.setText(_translate("MainWindow", "More", None))
        self.command_rm.setText(_translate("MainWindow", "More", None))
        self.command_rm_bk.setText(_translate("MainWindow", "Back", None))
        self.command_dm.setText(_translate("MainWindow", "More", None))
        self.command_dm_bk.setText(_translate("MainWindow", "Back", None))
        self.command_cr_bk.setText(_translate("MainWindow", "Back", None))
        self.command_cr.setText(_translate("MainWindow", "More", None))
        self.command_hr_bk.setText(_translate("MainWindow", "Back", None))
        self.command_hr.setText(_translate("MainWindow", "More", None))
        self.command_fic_bk.setText(_translate("MainWindow", "Back", None))
        self.command_fic.setText(_translate("MainWindow", "More", None))
        self.info_name.setText(_translate("MainWindow", "Title:", None))
        self.info_overview.setText(_translate("MainWindow", "Overview:", None))
        self.info_vote.setText(_translate("MainWindow", "Vote Average: ", None))
        self.info_date.setText(_translate("MainWindow", "Release Date: ", None))
